name: easy_rider
description: "A new Flutter project for easy ride."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase core package (required for initializing Firebase)
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Smooth Page Indicator for carousel indicators
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints to encourage good coding practices
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets for your project (like images)
  assets:
    - assets/images/bike.png
    - assets/images/user_pic.png
    - assets/images/bike_Home.png
    - assets/images/zany_face.png
